# -*- coding: utf-8 -*-
"""Unstructured Chicago.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bIsEqm7OC6um2T8oubw-k7WEQM-JyT2r
"""

from requests import get
response = get('https://chicago.craigslist.org/search/boo?')

from bs4 import BeautifulSoup
html_soup = BeautifulSoup(response.text, 'html.parser')

#get the macro-container for the housing posts
posts = html_soup.find_all('div', class_= 'result-info')
print(type(posts))
print(len(posts))

url1 = 'https://chicago.craigslist.org/search/boo?'

import requests
import bs4
 
url = 'https://chicago.craigslist.org/search/boo?'
 
res = requests.get(url)
res.raise_for_status()
soup = bs4.BeautifulSoup(res.text, 'html.parser')
 
for a in soup.find_all("a", class_="result-title hdrlnk"):
    print(a.string)
    print(a.get('href'))

listings = dict()
def addlisting(desc, url):
    if desc in listings:
        print('Already listed')
        print(desc)
    else:
        listings[desc] = url

def getSearchPageListings(url):
    res = requests.get(url)
    res.raise_for_status()
    html_soup = bs4.BeautifulSoup(res.text, 'html.parser')
    for a in soup.find_all("a", class_="result-title hdrlnk"):
        #print(a.string)
        addlisting(a.string, a.get('href'))

len(listings)

getSearchPageListings(url1)

def strip(txt):
    ret=""
    for l in txt.split("\n"):
        if l.strip()!='':
            ret += l + "\n"
    return ret

"""desc = strip(html_soup.get_text())
desc = desc[desc.find("OpenStreetMap")+13:desc.find("do NOT contact me with unsolicited services or offers")]
"""

urls = list(listings.values())

title = list(listings.keys())

bodysum = []
for a in urls:
#url2 = 'https://tippecanoe.craigslist.org/boa/d/lafayette-2008-yamaha-boats-232-limited/7309320473.html'
    #print(a)
    res = requests.get(a)
    res.raise_for_status()
    html_soup = bs4.BeautifulSoup(res.text, 'html.parser')
    desc = strip(html_soup.get_text())
    if (desc.find("QR Code Link to This Post") == -1):
        bodysum.append("NULL")
    else:
        bodysum.append(desc[desc.find("OpenStreetMap")+13:desc.find("do NOT contact me with unsolicited services or offers")])

import pandas as pd

chi_df = pd.DataFrame({'post title': title,
                        'URL': urls,
                       'desc': bodysum})
print(chi_df.info())
chi_df.head(10)

chi_df.to_csv('Chicago.csv')